package examples.facedetection;

// Import declarations generated by the SALSA compiler, do not modify.
import java.io.IOException;
import java.util.Vector;

import java.lang.reflect.Method;
import java.lang.reflect.Modifier;
import java.lang.reflect.InvocationTargetException;

import salsa.language.Actor;
import salsa.language.ActorReference;
import salsa.language.Message;
import salsa.language.RunTime;
import salsa.language.ServiceFactory;
import gc.WeakReference;
import salsa.language.Token;
import salsa.language.exceptions.*;
import salsa.language.exceptions.CurrentContinuationException;

import salsa.language.UniversalActor;

import salsa.naming.UAN;
import salsa.naming.UAL;
import salsa.naming.MalformedUALException;
import salsa.naming.MalformedUANException;

import salsa.resources.SystemService;

import salsa.resources.ActorService;

// End SALSA compiler generated import delcarations.

import java.util.ArrayList;

public class Phone_App_Manager extends UniversalActor  {
	public static void main(String args[]) {
		UAN uan = null;
		UAL ual = null;
		if (System.getProperty("uan") != null) {
			uan = new UAN( System.getProperty("uan") );
			ServiceFactory.getTheater();
			RunTime.receivedUniversalActor();
		}
		if (System.getProperty("ual") != null) {
			ual = new UAL( System.getProperty("ual") );

			if (uan == null) {
				System.err.println("Actor Creation Error:");
				System.err.println("	uan: " + uan);
				System.err.println("	ual: " + ual);
				System.err.println("	Identifier: " + System.getProperty("identifier"));
				System.err.println("	Cannot specify an actor to have a ual at runtime without a uan.");
				System.err.println("	To give an actor a specific ual at runtime, use the identifier system property.");
				System.exit(0);
			}
			RunTime.receivedUniversalActor();
		}
		if (System.getProperty("identifier") != null) {
			if (ual != null) {
				System.err.println("Actor Creation Error:");
				System.err.println("	uan: " + uan);
				System.err.println("	ual: " + ual);
				System.err.println("	Identifier: " + System.getProperty("identifier"));
				System.err.println("	Cannot specify an identifier and a ual with system properties when creating an actor.");
				System.exit(0);
			}
			ual = new UAL( ServiceFactory.getTheater().getLocation() + System.getProperty("identifier"));
		}
		RunTime.receivedMessage();
		Phone_App_Manager instance = (Phone_App_Manager)new Phone_App_Manager(uan, ual,null).construct();
		gc.WeakReference instanceRef=new gc.WeakReference(uan,ual);
		{
			Object[] _arguments = { args };

			//preAct() for local actor creation
			//act() for remote actor creation
			if (ual != null && !ual.getLocation().equals(ServiceFactory.getTheater().getLocation())) {instance.send( new Message(instanceRef, instanceRef, "act", _arguments, false) );}
			else {instance.send( new Message(instanceRef, instanceRef, "preAct", _arguments, false) );}
		}
		RunTime.finishedProcessingMessage();
	}

	public static ActorReference getReferenceByName(UAN uan)	{ return new Phone_App_Manager(false, uan); }
	public static ActorReference getReferenceByName(String uan)	{ return Phone_App_Manager.getReferenceByName(new UAN(uan)); }
	public static ActorReference getReferenceByLocation(UAL ual)	{ return new Phone_App_Manager(false, ual); }

	public static ActorReference getReferenceByLocation(String ual)	{ return Phone_App_Manager.getReferenceByLocation(new UAL(ual)); }
	public Phone_App_Manager(boolean o, UAN __uan)	{ super(false,__uan); }
	public Phone_App_Manager(boolean o, UAL __ual)	{ super(false,__ual); }
	public Phone_App_Manager(UAN __uan,UniversalActor.State sourceActor)	{ this(__uan, null, sourceActor); }
	public Phone_App_Manager(UAL __ual,UniversalActor.State sourceActor)	{ this(null, __ual, sourceActor); }
	public Phone_App_Manager(UniversalActor.State sourceActor)		{ this(null, null, sourceActor);  }
	public Phone_App_Manager()		{  }
	public Phone_App_Manager(UAN __uan, UAL __ual, Object obj) {
		//decide the type of sourceActor
		//if obj is null, the actor must be the startup actor.
		//if obj is an actorReference, this actor is created by a remote actor

		if (obj instanceof UniversalActor.State || obj==null) {
			  UniversalActor.State sourceActor;
			  if (obj!=null) { sourceActor=(UniversalActor.State) obj;}
			  else {sourceActor=null;}

			  //remote creation message sent to a remote system service.
			  if (__ual != null && !__ual.getLocation().equals(ServiceFactory.getTheater().getLocation())) {
			    WeakReference sourceRef;
			    if (sourceActor!=null && sourceActor.getUAL() != null) {sourceRef = new WeakReference(sourceActor.getUAN(),sourceActor.getUAL());}
			    else {sourceRef = null;}
			    if (sourceActor != null) {
			      if (__uan != null) {sourceActor.getActorMemory().getForwardList().putReference(__uan);}
			      else if (__ual!=null) {sourceActor.getActorMemory().getForwardList().putReference(__ual);}

			      //update the source of this actor reference
			      setSource(sourceActor.getUAN(), sourceActor.getUAL());
			      activateGC();
			    }
			    createRemotely(__uan, __ual, "examples.facedetection.Phone_App_Manager", sourceRef);
			  }

			  // local creation
			  else {
			    State state = new State(__uan, __ual);

			    //assume the reference is weak
			    muteGC();

			    //the source actor is  the startup actor
			    if (sourceActor == null) {
			      state.getActorMemory().getInverseList().putInverseReference("rmsp://me");
			    }

			    //the souce actor is a normal actor
			    else if (sourceActor instanceof UniversalActor.State) {

			      // this reference is part of garbage collection
			      activateGC();

			      //update the source of this actor reference
			      setSource(sourceActor.getUAN(), sourceActor.getUAL());

			      /* Garbage collection registration:
			       * register 'this reference' in sourceActor's forward list @
			       * register 'this reference' in the forward acquaintance's inverse list
			       */
			      String inverseRefString=null;
			      if (sourceActor.getUAN()!=null) {inverseRefString=sourceActor.getUAN().toString();}
			      else if (sourceActor.getUAL()!=null) {inverseRefString=sourceActor.getUAL().toString();}
			      if (__uan != null) {sourceActor.getActorMemory().getForwardList().putReference(__uan);}
			      else if (__ual != null) {sourceActor.getActorMemory().getForwardList().putReference(__ual);}
			      else {sourceActor.getActorMemory().getForwardList().putReference(state.getUAL());}

			      //put the inverse reference information in the actormemory
			      if (inverseRefString!=null) state.getActorMemory().getInverseList().putInverseReference(inverseRefString);
			    }
			    state.updateSelf(this);
			    ServiceFactory.getNaming().setEntry(state.getUAN(), state.getUAL(), state);
			    if (getUAN() != null) ServiceFactory.getNaming().update(state.getUAN(), state.getUAL());
			  }
		}

		//creation invoked by a remote message
		else if (obj instanceof ActorReference) {
			  ActorReference sourceRef= (ActorReference) obj;
			  State state = new State(__uan, __ual);
			  muteGC();
			  state.getActorMemory().getInverseList().putInverseReference("rmsp://me");
			  if (sourceRef.getUAN() != null) {state.getActorMemory().getInverseList().putInverseReference(sourceRef.getUAN());}
			  else if (sourceRef.getUAL() != null) {state.getActorMemory().getInverseList().putInverseReference(sourceRef.getUAL());}
			  state.updateSelf(this);
			  ServiceFactory.getNaming().setEntry(state.getUAN(), state.getUAL(),state);
			  if (getUAN() != null) ServiceFactory.getNaming().update(state.getUAN(), state.getUAL());
		}
	}

	public UniversalActor construct () {
		Object[] __arguments = {  };
		this.send( new Message(this, this, "construct", __arguments, null, null) );
		return this;
	}

	public class State extends UniversalActor .State {
		public Phone_App_Manager self;
		public void updateSelf(ActorReference actorReference) {
			((Phone_App_Manager)actorReference).setUAL(getUAL());
			((Phone_App_Manager)actorReference).setUAN(getUAN());
			self = new Phone_App_Manager(false,getUAL());
			self.setUAN(getUAN());
			self.setUAL(getUAL());
			self.activateGC();
		}

		public State() {
			this(null, null);
		}

		public State(UAN __uan, UAL __ual) {
			super(__uan, __ual);
			addClassName( "examples.facedetection.Phone_App_Manager$State" );
			addMethodsForClasses();
		}

		public void process(Message message) {
			Method[] matches = getMatches(message.getMethodName());
			Object returnValue = null;
			Exception exception = null;

			if (matches != null) {
				if (!message.getMethodName().equals("die")) {activateArgsGC(message);}
				for (int i = 0; i < matches.length; i++) {
					try {
						if (matches[i].getParameterTypes().length != message.getArguments().length) continue;
						returnValue = matches[i].invoke(this, message.getArguments());
					} catch (Exception e) {
						if (e.getCause() instanceof CurrentContinuationException) {
							sendGeneratedMessages();
							return;
						} else if (e instanceof InvocationTargetException) {
							sendGeneratedMessages();
							exception = (Exception)e.getCause();
							break;
						} else {
							continue;
						}
					}
					sendGeneratedMessages();
					currentMessage.resolveContinuations(returnValue);
					return;
				}
			}

			System.err.println("Message processing exception:");
			if (message.getSource() != null) {
				System.err.println("\tSent by: " + message.getSource().toString());
			} else System.err.println("\tSent by: unknown");
			System.err.println("\tReceived by actor: " + toString());
			System.err.println("\tMessage: " + message.toString());
			if (exception == null) {
				if (matches == null) {
					System.err.println("\tNo methods with the same name found.");
					return;
				}
				System.err.println("\tDid not match any of the following: ");
				for (int i = 0; i < matches.length; i++) {
					System.err.print("\t\tMethod: " + matches[i].getName() + "( ");
					Class[] parTypes = matches[i].getParameterTypes();
					for (int j = 0; j < parTypes.length; j++) {
						System.err.print(parTypes[j].getName() + " ");
					}
					System.err.println(")");
				}
			} else {
				System.err.println("\tThrew exception: " + exception);
				exception.printStackTrace();
			}
		}

		long serialVersionUID = 1L;
		String name_server;
		String phone_theater;
		String remote_theater;
		String[] image_names;
		boolean isReporting;
		String report_theater;
		String status;
		Reporter_Actor reporter_actor;
		int no_local_workers;
		int no_remote_workers;
		long startTime, finalTime, total_run_time;
		ArrayList face_detector_workers = new ArrayList();
		ArrayList images = new ArrayList();
		int finished_face_detector_workers;
		Exp_Starter exp_starter = null;
		public void construct(){
			total_run_time = -1;
			finalTime = -1;
			startTime = -1;
			this.no_local_workers = 0;
			this.no_remote_workers = 0;
			finished_face_detector_workers = 0;
		}
		public void start_app(Exp_Starter exp_st, String args[]) {
			this.setStatus("RUNNING");
			exp_starter = exp_st;
			{
				Token token_2_0 = new Token();
				// standardOutput<-println("PHONE_APP: App started.")
				{
					Object _arguments[] = { "PHONE_APP: App started." };
					Message message = new Message( self, standardOutput, "println", _arguments, null, token_2_0 );
					__messages.add( message );
				}
				// standardOutput<-println("PHONE_APP: Experiment 22 Ver. 3")
				{
					Object _arguments[] = { "PHONE_APP: Experiment 22 Ver. 3" };
					Message message = new Message( self, standardOutput, "println", _arguments, token_2_0, null );
					__messages.add( message );
				}
			}
			int argc = args.length;
			if (argc<8) {{
				{
					// standardOutput<-println("PHONE_APP: Correct call requires following arguments: [name_server] [phone_theater] [remote_theater] "+" [no_local_actors] [no_remote_actors] [image_names] [report_on/report_off] [report_theater]")
					{
						Object _arguments[] = { "PHONE_APP: Correct call requires following arguments: [name_server] [phone_theater] [remote_theater] "+" [no_local_actors] [no_remote_actors] [image_names] [report_on/report_off] [report_theater]" };
						Message message = new Message( self, standardOutput, "println", _arguments, null, null );
						__messages.add( message );
					}
				}
				this.setStatus("FAILED: Wrong number of initial calling arguments.");
			}
}			name_server = args[0];
			phone_theater = args[1];
			remote_theater = args[2];
			no_local_workers = Integer.parseInt(args[3]);
			no_remote_workers = Integer.parseInt(args[4]);
			image_names = new String[argc-7];
			for (int i = 0; i<image_names.length; i++){
				image_names[i] = args[5+i];
				images.add(args[5+i]);
			}
			if (args[argc-2].equalsIgnoreCase("report_on")) {{
				isReporting = true;
			}
}			else {{
				isReporting = false;
			}
}			report_theater = args[argc-1];
			reporter_actor = ((Reporter_Actor)new Reporter_Actor(new UAN(name_server+"reporter"), new UAL(report_theater+"reporter"),this).construct());
			{
				// standardOutput<-println("PHONE_APP: Par. Face Det. Comp. started...")
				{
					Object _arguments[] = { "PHONE_APP: Par. Face Det. Comp. started..." };
					Message message = new Message( self, standardOutput, "println", _arguments, null, null );
					__messages.add( message );
				}
			}
			this.report("Starting Parallel Face Detection Experiment");
			startTime = System.currentTimeMillis();
			for (int i = 0; i<no_local_workers; i++){
				Face_Detector fd = ((Face_Detector)new Face_Detector(new UAN(name_server+"LocalFaceDetector"+i),this).construct(reporter_actor, isReporting));
				face_detector_workers.add(fd);
			}
			for (int i = 0; i<no_remote_workers; i++){
				Face_Detector fd = ((Face_Detector)new Face_Detector(new UAN(name_server+"RemoteFaceDetector"+i), new UAL(remote_theater+"RemoteFaceDetector"+i),this).construct(reporter_actor, isReporting));
				face_detector_workers.add(fd);
			}
			for (int i = 0; i<face_detector_workers.size(); i++){
				{
					// face_detector_workers.get(i)<-start_up(((Phone_App_Manager)self))
					{
						Object _arguments[] = { ((Phone_App_Manager)self) };
						Message message = new Message( self, face_detector_workers.get(i), "start_up", _arguments, null, null );
						__messages.add( message );
					}
				}
			}
		}
		public String get_image() {
			if (images.size()>0) {{
				return (String)images.remove(0);
			}
}			else {{
				finished_face_detector_workers++;
				if (finished_face_detector_workers==face_detector_workers.size()) {{
					{
						// ((Phone_App_Manager)self)<-wrap_up()
						{
							Object _arguments[] = {  };
							Message message = new Message( self, ((Phone_App_Manager)self), "wrap_up", _arguments, null, null );
							__messages.add( message );
						}
					}
				}
}				return null;
			}
}		}
		public void wrap_up() {
			this.endTimer();
			this.setStatus("SUCCESS");
			this.report("PHONE_APP: Phone App. Manager Finished.");
			{
				// standardOutput<-println("PHONE_APP: Phone App. Manager Finished.")
				{
					Object _arguments[] = { "PHONE_APP: Phone App. Manager Finished." };
					Message message = new Message( self, standardOutput, "println", _arguments, null, null );
					__messages.add( message );
				}
			}
			{
				// exp_starter<-wrap_up(total_run_time, status)
				{
					Object _arguments[] = { total_run_time, status };
					Message message = new Message( self, exp_starter, "wrap_up", _arguments, null, null );
					__messages.add( message );
				}
			}
		}
		public void report(String msg) {
			if (isReporting) {			{
				// reporter_actor<-report(msg)
				{
					Object _arguments[] = { msg };
					Message message = new Message( self, reporter_actor, "report", _arguments, null, null );
					__messages.add( message );
				}
			}
}		}
		public void setStatus(String m) {
			status = m;
		}
		public String getStatus() {
			return status;
		}
		public void endTimer() {
			finalTime = System.currentTimeMillis();
			total_run_time = finalTime-startTime;
		}
		public void dummy() {
		}
		public void dummy_collectToken(Object[] res) {
		}
	}
}